name: sql_connection_example
description: "Demonstrates how to use the sql_connection plugin."

publish_to: "none"

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter

  sql_connection:
    path: ../
  flutter_json_view: ^1.1.5
  cupertino_icons: ^1.0.8

dev_dependencies:
  integration_test:
    sdk: flutter
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
