name: sql_connection
description: "A package that connects to JDBC SQL Server databases is a software component that provides the necessary functionality to establish and manage a connection between a Java application and a Microsoft SQL Server database using the Java Database Connectivity (JDBC) API."
version: 1.0.0
homepage: "https://github.com/bijithpn/sql_connection_package"

environment:
  sdk: ^3.5.3
  flutter: ">=3.3.0"

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  plugin:
    platforms:
      android:
        package: com.example.sql_connection
        pluginClass: SqlConnectionPlugin
